### ISSUE TITLE
Tagged Versions

### ISSUE THREAD

**Issue by jakeasmith** [DaveChild/Text-Statistics#29]
Hi there! Thanks for a really useful package, we really appreciate it. Would you be willing to tag a first version (even if its a beta 0.1.0) on the project? I'd like to use this in production but pulling it in thru composer using `dev-master` is a bit risky. If I were to run a `composer update` and pull in a breaking change without noticing it I would have some very unhappy customers. That'd be bad.

Thanks again for the package and your consideration :)

**Comment by squinones** [comment]
+1

**Comment by ralouphie** [comment]
+1 That would be very useful.

**Comment by shashikreddy** [comment]
+1

**Comment by DaveChild** [comment]
Sounds like this is a popular idea, Jake. Thanks! It'll take me a little while, as I have no idea how git tags translate into composer versions, but I should have something ready to implement this week.

**Comment by DaveChild** [comment]
Ok, I've added a tag, starting at 1.0.0 (this has been around long enough now that 1.* felt about right). Can you let me know if that's behaving correctly for you?

**Comment by jakeasmith** [comment]
:boom: Perfect. Just pulled in `1.0.1`. Thanks for the quick response on this! I feel a lot better about putting this into prod now :)
