### ISSUE TITLE
incorrectly considered SMOG

### ISSUE THREAD

**Issue by an19drey** [DaveChild/Text-Statistics#33]
Hellow. Incorrectly considered SMOG. Сheck formula whith https://en.wikipedia.org/wiki/SMOG.

**Comment by an19drey** [comment]
$score =Maths::bcCalc( 
                Maths::bcCalc(
            1.043,
            '*',
            Maths::bcCalc(
                    Maths::bcCalc(
                        Syllables::wordsWithThreeSyllables($strText, true, $this->strEncoding),
                        '*',
                        Maths::bcCalc(
                            30,
                            '/',
                            Text::sentenceCount($strText, $this->strEncoding)
                        )
                    ),
                    'sqrt',
                    0
            )
        ),
        '+',
        3.129
        );

**Comment by DaveChild** [comment]
That looks spot on to me. What do you think is incorrect?

**Comment by an19drey** [comment]
![image](https://cloud.githubusercontent.com/assets/8956820/12782208/357cfa60-ca82-11e5-8566-7c5948c51cfe.png)
Your code (see 3.1291):

        $score = Maths::bcCalc(
            1.043,
            '*',
            Maths::bcCalc(
                Maths::bcCalc(
                    Maths::bcCalc(
                        Syllables::wordsWithThreeSyllables($strText, true, $this->strEncoding),
                        '*',
                        Maths::bcCalc(
                            30,
                            '/',
                            Text::sentenceCount($strText, $this->strEncoding)
                        )
                    ),
                    '+',
                    3.1291
                ),
                'sqrt',
                0
            )
        );
