### ISSUE TITLE
Addition of Läsbarhetsindex

### ISSUE THREAD

**Issue by Nio-av** [DaveChild/Text-Statistics#38]
I've writen code for calculating the _Läsbarhetsindex_ (Björnsson, 1968).

```
LIX = 100*RWL+ASL

*Where*
RLW (Ratio of long Words to all words) = Number of Long Words / Number of Words
ASL (Average sentence length) = number of Words / Number of Sentences

and: Long Words have more than six characters.
```
This Readability-Score formula has been developed for Swedish, but also works for German and English. More Informations:
> Ott,N.(2009). Information retrieval for language learning: An exploration of text difficulty measures. In ISCL master’s thesis. Universität Tübingen, Seminar für Sprachwissenschaft, Tübingen, Germany. Page 19

May I commit this additions direct to master-branch?

**Comment by DaveChild** [comment]
Absolutely, thanks for adding it!

**Comment by Nio-av** [comment]
See Pull Request #39. I haven't write access to this Repository.
