### ISSUE TITLE
Semver?

### ISSUE THREAD

**Issue by timkelty** [DaveChild/Text-Statistics#48]
It would be great if this project's version adhered to some kind of semantic versioning.

I had projects that were requiring `^1.0.2`, that suddenly broke because there was a breaking change in a patch release (1.0.2 to 1.0.3).

I see now that you have a note in the readme to specify 1.0.2 explicitly if you need < 7.2 support, but that wouldn't even be necessary to call out semver more strictly followed.

**Comment by khalwat** [comment]
I'm with you on the semver.

Appreciate all your hard work @DaveChild

**Comment by DaveChild** [comment]
That's a fair point, and sorry, I should have considered that. I'll be more careful in future!

**Comment by timkelty** [comment]
I appreciate it, thanks!
